### ISSUE TITLE
adding origin loading time to the logs

### ISSUE THREAD

**Issue by boynet** [boynet/cf-logdna-worker#6]
its good idae to follow the origin loading time to detect problems at the origin

**Comment by adaptive** [comment]
When debugging I send the running time to the header.
initiate within the handle function
`const requestStart = Date.now();`

and then on the header of the response
`'X-upstream-latency': Date.now() - requestStart,`

Note: that this isn't what Cloudflare refers as CPU time.

**Comment by boynet** [comment]
added in https://github.com/boynet/cf-logdna-worker/commit/0c72ecf06a1cc3fe5962c7cc5ec821334341c22e
